### ISSUE TITLE
Unable to launch with latest version: No module named 'comfy.sd2_clip'

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [nkchocoai/ComfyUI-SaveImageWithMetaData#26]
```
Torch version: 2.3.1+cu121
Traceback (most recent call last):
  File "C:\AI\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\__init__.py", line 1, in <module>
    from .py.nodes.node import SaveImageWithMetaData
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\__init__.py", line 3, in <module>
    from .hook import pre_execute, pre_get_input_data
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\hook.py", line 1, in <module>
    from .nodes.node import SaveImageWithMetaData
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 19, in <module>
    from ..capture import Capture
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\capture.py", line 5, in <module>
    from .defs.captures import CAPTURE_FIELD_LIST
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\__init__.py", line 5, in <module>
    from .captures import CAPTURE_FIELD_LIST
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\captures.py", line 3, in <module>
    from .formatters import (
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\formatters.py", line 10, in <module>
    from comfy.sd2_clip import SD2Tokenizer
ModuleNotFoundError: No module named 'comfy.sd2_clip'

Cannot import C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData module for custom nodes: No module named 'comfy.sd2_clip'
```

**Comment by nkchocoai** [comment]
I fixed it.

Related Commit : 
https://github.com/comfyanonymous/ComfyUI/commit/4ba7fa0244badcf901f2b8ddbfb8539c6398672f

**Comment by MNeMoNiCuZ** [comment]
Confirmed working again. Brilliant <3
