### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by kannith** [nkchocoai/ComfyUI-SaveImageWithMetaData#29]
When starting ComfyUI, this node fails to load for some reason. in the log i get:

`[2024-08-03 01:31] Traceback (most recent call last):
  File "C:\ComfyUI\nodes.py", line 1907, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\__init__.py", line 1, in <module>
    from .py.nodes.node import SaveImageWithMetaData
  File "C:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\__init__.py", line 3, in <module>
    from .hook import pre_execute, pre_get_input_data
  File "C:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\hook.py", line 1, in <module>
    from .nodes.node import SaveImageWithMetaData
  File "C:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 19, in <module>
    from ..capture import Capture
  File "C:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\capture.py", line 5, in <module>
    from .defs.captures import CAPTURE_FIELD_LIST
  File "C:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\__init__.py", line 5, in <module>
    from .captures import CAPTURE_FIELD_LIST
  File "C:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\captures.py", line 3, in <module>
    from .formatters import (
  File "C:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\formatters.py", line 10, in <module>
    from comfy.text_encoders.sd2_clip import SD2Tokenizer
ModuleNotFoundError: No module named 'comfy.text_encoders'`

**Comment by nkchocoai** [comment]
Please update ComfyUI
Related Issue : https://github.com/nkchocoai/ComfyUI-SaveImageWithMetaData/issues/26
