### ISSUE TITLE
Error when saving 

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [nkchocoai/ComfyUI-SaveImageWithMetaData#37]
I'm getting an error when saving the image with this checkpoint: https://civitai.com/models/673188

I'm using the `Load Diffusion Model` to load the checkpoint.

It saves fine with the normal save node.

```
Error occurred when executing SaveImageWithMetaData:

expected str, bytes or os.PathLike object, not NoneType

  File "C:\AI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 79, in save_images
    pnginfo_dict_src = self.gen_pnginfo(
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 165, in gen_pnginfo
    inputs = Capture.get_inputs()
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\capture.py", line 64, in get_inputs
    v = format(v, input_data)
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\formatters.py", line 18, in calc_model_hash
    return calc_hash(filename)
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\utils\hash.py", line 12, in calc_hash
    with open(filename, "rb") as f:
```

**Comment by ardri1166** [comment]
Getting the same error as of this morning. A few hours ago everything worked fine.

!!! Exception during processing !!! expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 79, in save_images
    pnginfo_dict_src = self.gen_pnginfo(
                       ^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 165, in gen_pnginfo
    inputs = Capture.get_inputs()
             ^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\capture.py", line 65, in get_inputs
    v = format(v, input_data)
        ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\formatters.py", line 61, in extract_embedding_hashes
    embedding_hashes.append(calc_hash(embedding_file_path))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\utils\hash.py", line 12, in calc_hash
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ardri1166** [comment]
I wonder what is going on with this node. It is by far my favourite, but the fact that it breaks every other day then works again for 2 days is just disappointing.

**Comment by MNeMoNiCuZ** [comment]
> I wonder what is going on with this node. It is by far my favourite, but the fact that it breaks every other day then works again for 2 days is just disappointing.

Then look into fixing it :)

**Comment by nkchocoai** [comment]
I used the workflow here, but could not reproduce it.
https://comfyanonymous.github.io/ComfyUI_examples/flux/flux_dev_example.png

Please give me the workflow when the error occurred.

**Comment by MNeMoNiCuZ** [comment]
```
Error occurred when executing SaveImageWithMetaData:

'NoneType' object has no attribute 'tokenizer'

  File "C:\AI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\AI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 81, in save_images
    pnginfo_dict_src = self.gen_pnginfo(
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 167, in gen_pnginfo
    inputs = Capture.get_inputs()
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\capture.py", line 65, in get_inputs
    v = format(v, input_data)
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\formatters.py", line 51, in extract_embedding_names
    embedding_names, _ = _extract_embedding_names(text, input_data)
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\formatters.py", line 68, in _extract_embedding_names
    tokenizer = clip.tokenizer
```

Workflow in image:
![workflow(1)](https://github.com/user-attachments/assets/840c7675-9047-4e3a-8bcd-236931f13862)


Not sure when it happens, but it happens whenever I try to generate 2 different versions (one with a lora, and one without a lora for example), to make comparison images to see the effect of a LoRA, or compare different versions of LoRAs.

**Comment by ardri1166** [comment]
> I used the workflow here, but could not reproduce it. https://comfyanonymous.github.io/ComfyUI_examples/flux/flux_dev_example.png
> 
> Please give me the workflow when the error occurred.

I came home from work and it worked for exactly 5 images. Then the error came back. WF attached.

[workflow.json](https://github.com/user-attachments/files/16802785/workflow.json)

**Comment by ardri1166** [comment]
At the risk of someone mocking me again for not having any clue how coding works, this one eludes me. Without changing a thing, it works for some images and not for others.

**Comment by MNeMoNiCuZ** [comment]
> At the risk of someone mocking me again for not having any clue how coding works, this one eludes me. Without changing a thing, it works for some images and not for others.

There was no mocking about coding, it was more an attitude and appreciation for the works of others issue.

---

**Regarding this message:** 
I've had the same thing. I can be running a workflow, and then suddenly I get an error with the save node and the workflow stops working and I have to restart it.

**Comment by ardri1166** [comment]
As I mentioned before this is one of my favourite nodes. So I did some more testing just now and realised that the saving only breaks when embeddings are used. I've seen another issue thread on this topic which was just recently closed but I'm not sure if they're connected.

Here 2 wf with and without embeddings.
[with embed.json](https://github.com/user-attachments/files/16823914/with.embed.json)
[no embed.json](https://github.com/user-attachments/files/16823916/no.embed.json)

**Comment by MNeMoNiCuZ** [comment]
> As I mentioned before this is one of my favourite nodes. So I did some more testing just now and realised that the saving only breaks when embeddings are used. I've seen another issue thread on this topic which was just recently closed but I'm not sure if they're connected.
> 
> Here 2 wf with and without embeddings. [with embed.json](https://github.com/user-attachments/files/16823914/with.embed.json) [no embed.json](https://github.com/user-attachments/files/16823916/no.embed.json)

Ah, I think this matches my issues as well.
I think I may be getting the issues when I'm doing LoRA comparisons.

Nice find!

**Comment by NeoAnthropocene** [comment]
Interestingly the `SaveImageWithMetaData `does not work when we use LoRa or Embeddings.

It throws out this error:


# ComfyUI Error Report
## Error Details
- **Node Type:** SaveImageWithMetaData
- **Exception Type:** TypeError
- **Exception Message:** expected str, bytes or os.PathLike object, not NoneType
## Stack Trace
```
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 83, in save_images
    pnginfo_dict_src = self.gen_pnginfo(

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 175, in gen_pnginfo
    inputs = Capture.get_inputs()

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\capture.py", line 47, in get_inputs
    v = selector(

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\ext\rgthree.py", line 11, in get_lora_model_hash
    return [

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\ext\rgthree.py", line 12, in <listcomp>
    calc_lora_hash(model_name, input_data)

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\formatters.py", line 30, in calc_lora_hash
    return calc_hash(filename)

  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\utils\hash.py", line 12, in calc_hash
    with open(filename, "rb") as f:

```
## System Information
- **ComfyUI Version:** v0.2.4-2-g915fdb5
- **Arguments:** ComfyUI\main.py --windows-standalone-build --reserve-vram 1.0 --fast --front-end-version Comfy-Org/ComfyUI_frontend@latest
- **OS:** nt
- **Python Version:** 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 6139364918
  - **Torch VRAM Total:** 9563013120
  - **Torch VRAM Free:** 35604022

## Logs
```
2024-10-24 11:44:37,039 - root - INFO - Total VRAM 16376 MB, total RAM 32517 MB
2024-10-24 11:44:37,039 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-24 11:44:38,271 - root - INFO - xformers version: 0.0.28.post1
2024-10-24 11:44:38,271 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-24 11:44:38,271 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
2024-10-24 11:44:38,480 - root - INFO - Using xformers cross attention
2024-10-24 11:44:39,153 - root - INFO - Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
2024-10-24 11:44:39,491 - root - INFO - [Prompt Server] web root: ~HIDDEN~\ComfyUI_windows_portable\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.21

2024-10-24 12:06:17,671 - root - INFO - got prompt
2024-10-24 12:06:18,006 - root - INFO - Requested to load FluxClipModel_
2024-10-24 12:06:18,006 - root - INFO - Loading 1 new model
2024-10-24 12:06:19,247 - root - INFO - loaded completely 0.0 4777.7880859375 True
2024-10-24 12:06:19,444 - root - INFO - Requested to load Flux
2024-10-24 12:06:19,445 - root - INFO - Loading 1 new model
2024-10-24 12:06:30,164 - root - INFO - loaded completely 0.0 11350.048889160156 True
2024-10-24 12:06:41,499 - root - INFO - Requested to load AutoencodingEngine
2024-10-24 12:06:41,500 - root - INFO - Loading 1 new model
2024-10-24 12:06:41,558 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-10-24 12:06:41,909 - root - ERROR - !!! Exception during processing !!! expected str, bytes or os.PathLike object, not NoneType
2024-10-24 12:06:41,910 - root - ERROR - Traceback (most recent call last):
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 83, in save_images
    pnginfo_dict_src = self.gen_pnginfo(
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 175, in gen_pnginfo
    inputs = Capture.get_inputs()
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\capture.py", line 47, in get_inputs
    v = selector(
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\ext\rgthree.py", line 11, in get_lora_model_hash
    return [
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\ext\rgthree.py", line 12, in <listcomp>
    calc_lora_hash(model_name, input_data)
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\defs\formatters.py", line 30, in calc_lora_hash
    return calc_hash(filename)
  File "~HIDDEN~\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\utils\hash.py", line 12, in calc_hash
    with open(filename, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ardri1166** [comment]
Has been working flawlessly for me for several weeks now with normal workflows, Flux and everything in between.

**Comment by CJohnDesign** [comment]
Same error: 

# ComfyUI Error Report
## Error Details
- **Node Type:** SaveImageWithMetaData
- **Exception Type:** TypeError
- **Exception Message:** join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
## Stack Trace

**Comment by Cryyc** [comment]
Created a pull request with a fix for this error just to let you know.
