### ISSUE TITLE
Error: Key Error -1

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [nkchocoai/ComfyUI-SaveImageWithMetaData#43]
```
SaveImageWithMetaData
-1
```

```
# ComfyUI Error Report
## Error Details
- **Node Type:** SaveImageWithMetaData
- **Exception Type:** KeyError
- **Exception Message:** -1
## Stack Trace
  File "C:\AI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\AI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 83, in save_images
    pnginfo_dict_src = self.gen_pnginfo(

  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 191, in gen_pnginfo
    trace_tree_from_sampler_node = Trace.trace(sampler_node_id, hook.current_prompt)

  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\trace.py", line 10, in trace
    class_type = prompt[start_node_id]["class_type"]
```

```
2024-09-22 15:34:17,437 - root - ERROR - !!! Exception during processing !!! -1
2024-09-22 15:34:17,437 - root - ERROR - Traceback (most recent call last):
  File "C:\AI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\AI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 83, in save_images
    pnginfo_dict_src = self.gen_pnginfo(
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 191, in gen_pnginfo
    trace_tree_from_sampler_node = Trace.trace(sampler_node_id, hook.current_prompt)
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\trace.py", line 10, in trace
    class_type = prompt[start_node_id]["class_type"]
KeyError: -1
```

I was trying to use the `Flux Sampler Parameters` node so that I could save XY-grids of the images. But then the SaveImageWithMetadata node broke.

Workflow JSON: [Flux-XY.json](https://github.com/user-attachments/files/17089877/Flux-XY.json)

**Comment by Jonseed** [comment]
I also get this error. Any fix for it?

**Comment by KY-Chan** [comment]
This custom node automatically detect sampler and get parameters (like positive prompt, sampler, cfg).
How can it works....it's hard coded.
If you are using custom sampler that's not in hard coded samplers, this node can't find sampler,

ComfyUI-ImageMetadataExtension\py\defs\samplers.py
ComfyUI-ImageMetadataExtension\py\defs\captures.py

I put my custom sampler name in these files manually,
and it works, but there are only 2 parameters saved in img File.  CFG and sampler.

Since I'm not familiar with Python and debugging ComfyUI, so I'll stop here and give up.

**Comment by TeaKae** [comment]
I got this error when using a pipe ksampler, the node didn't seem to like it. Issued got fixed when I switched to a different ksampler node.

**Comment by miurgh** [comment]
FaceDetailer--------work
Detailer(SEGS)--not work

sampler_selection_method is not involved.

**Comment by bruebakerr** [comment]
I was testing out replacement samplers in a workflow that had been working for some time I too started getting the -1 error condition.  The _Troubleshooting Long Story Short_ as to why it works with one sampler and another is that the node is _programed_ to look for specific samplers and if it doesn't find it a matching sampler then it tosses this error (comes from the functions in `trace.py` file).

Looking around I found that the `py\defs\samplers.py` file contains the following list of samplers.

```
SAMPLERS = {
    "KSampler": {
        "positive": "positive",
        "negative": "negative",
    },
    "KSamplerAdvanced": {
        "positive": "positive",
        "negative": "negative",
    },
    # Flux - https://comfyanonymous.github.io/ComfyUI_examples/flux/
    "SamplerCustomAdvanced": {
        "positive": "guider",
    },
}
```

The quick and dirty fix for this node to play nice with other samplers is to add them to the `samplers.py` file.  In my case I was trying some sampler nodes from the CG Noise, Inspire-Pack, and YANC node packs, so my `sampler.py` file was updated to the following

```
SAMPLERS = {
    "KSampler": {
        "positive": "positive",
        "negative": "negative",
    },
    "KSamplerAdvanced": {
        "positive": "positive",
        "negative": "negative",
    },
    # Flux - https://comfyanonymous.github.io/ComfyUI_examples/flux/
    "SamplerCustomAdvanced": {
        "positive": "guider",
    },
    "KSampler Advanced with Variations": {
        "positive": "positive",
        "negative": "negative",
    },    
    "KSampler with Variations": {
        "positive": "positive",
        "negative": "negative",
    },
    "KSampler //Inspire": {
        "positive": "positive",
        "negative": "negative",
    },
     "> NIKSampler": {
        "positive": "positive",
        "negative": "negative",
    }, 
}
```

This is all well and good **IF** the sampler node(s) you are adding doesn't tweak anything on the various output names (e.g., CG Noise introduces variation seed).  For this you may experience ComfyUI throwing an `UnboundLocalError: local variable 'sampler' referenced before assignment`.  This comes from a result of the `inputs_before_sampler_node` value in the `gen_pnginfo_dict` function in `capture.py`

Should look something like this:

> `inputs_before_sampler_node <class 'dict'>: {<MetaField.MODEL_NAME: 0>: [('4', 'sdxl\\dreamshaperXL_v21TurboDPMSDE.safetensors', 5)], <MetaField.MODEL_HASH: 1>: [('4', '4496b36d48', 5)], <MetaField.IMAGE_WIDTH: 30>: [('5', 1024, 4)], <MetaField.IMAGE_HEIGHT: 31>: [('5', 1024, 4)], <MetaField.POSITIVE_PROMPT: 10>: [('6', 'portrait of a woman in an encahnted forest, magical, fantasy, rpg, glowing, high detail, intricate, cinematic quality', 4)], <MetaField.NEGATIVE_PROMPT: 11>: [('7', 'text, watermark, horror, ill, nude, nsfw', 4)], <MetaField.SEED: 20>: [('27', 863666330125481, 3)], <MetaField.STEPS: 21>: [('27', 20, 3)], <MetaField.CFG: 22>: [('27', 8.0, 3)], <MetaField.SAMPLER_NAME: 23>: [('27', 'euler', 3)], <MetaField.SCHEDULER: 24>: [('27', 'normal', 3)]}`

But when there is a variation of the sampler node you'll get something like this where the metadata information is lost .... hence the sampler variable (in this case derived from the MetaField.SAMPLER_NAME) is missing and returns the corresponding error:

> `inputs_before_sampler_node <class 'dict'>: {<MetaField.MODEL_NAME: 0>: [('4', 'sdxl\\dreamshaperXL_v21TurboDPMSDE.safetensors', 2)], <MetaField.MODEL_HASH: 1>: [('4', '4496b36d48', 2)], <MetaField.IMAGE_WIDTH: 30>: [('5', 1024, 1)], <MetaField.IMAGE_HEIGHT: 31>: [('5', 1024, 1)], <MetaField.POSITIVE_PROMPT: 10>: [('6', 'portrait of a woman in an encahnted forest, magical, fantasy, rpg, glowing, high detail, intricate, cinematic quality', 1)], <MetaField.NEGATIVE_PROMPT: 11>: [('7', 'text, watermark, horror, ill, nude, nsfw', 1)]}`

To solve this, it'll take a bit of trial-and-error along with a little detective work to pull the sampler node's specific details which can be done by examining the corresponding Node ID of image's prompt information which can be displayed in logs by adding the following print command to the `trace.py` file :

```
class Trace:
    @classmethod
    def trace(cls, start_node_id, prompt):
        print(f'prompt {type(prompt)}: {prompt}')
```

The details of my node in question were as follows _(this information should line up with the field names in the node in ComfyUI ... but this gives you what the underlying code is seeing!!!)_.  You can see it is using `variation_seed` :

> `'40': {'inputs': {'seed': 1049028048992918, 'steps': 20, 'cfg': 8.0, 'sampler_name': 'euler', 'scheduler': 'normal', 'denoise': 1.0, 'noise_mode': 'GPU(=A1111)', 'batch_seed_mode': 'incremental', 'variation_seed': 622185713573706, 'variation_strength': 0.0, 'variation_method': 'linear', 'internal_seed': 0, 'model': ['4', 0], 'positive': ['6', 0], 'negative': ['7', 0], 'latent_image': ['5', 0]}, 'class_type': 'KSampler //Inspire', '_meta': {'title': 'KSampler (inspire)'}},`

This is where the trial-and-error occurs .... to get rid of the `UnboundLocalError: local variable 'sampler' referenced before assignment` error, you'll need to add a new file to the `\py\defs\ext` directory that includes:

- List of the non-standard samplers
- Extract list of key metadata fields to include

Testing showed that not including the various metadata fields would not fully populate the `inputs_before_sampler_node` value which is used to slice and dice the data by the `SaveImageWithMetaData` node.  This file gets _sucked_ in when the node loads information to capture LORA stacks, etc. (REF: #25, #30). To get the samplers with variation seeds to play nice with my workflows and to finally get Save Image With MetaData to function properly, my added file looked like the following:

```
from ..meta import MetaField

SAMPLERS = {
    "KSampler Advanced with Variations": {
        "positive": "positive",
        "negative": "negative",
    },    
    "KSampler with Variations": {
        "positive": "positive",
        "negative": "negative",
    },
    "KSampler //Inspire": {
        "positive": "positive",
        "negative": "negative",
    },    
}

CAPTURE_FIELD_LIST = {
    "KSampler Advanced with Variations": {
        MetaField.SEED: {"field_name": "noise_seed"},
        MetaField.VARIATION_SEED: {"field_name": "variation_seed"},
        MetaField.VARIATION_STRENGTH: {"field_name": "variation_weight"},
        MetaField.STEPS: {"field_name": "steps"},
        MetaField.CFG: {"field_name": "cfg"},
        MetaField.SAMPLER_NAME: {"field_name": "sampler_name"},
        MetaField.SCHEDULER: {"field_name": "scheduler"},  
    },
    "KSampler with Variations": {
        MetaField.SEED: {"field_name": "seed"},
        MetaField.VARIATION_SEED: {"field_name": "variation_seed"},
        MetaField.VARIATION_STRENGTH: {"field_name": "variation_weight"},
        MetaField.STEPS: {"field_name": "steps"},
        MetaField.CFG: {"field_name": "cfg"},
        MetaField.SAMPLER_NAME: {"field_name": "sampler_name"},
        MetaField.SCHEDULER: {"field_name": "scheduler"},  
    },
    "KSampler //Inspire": {
        MetaField.SEED: {"field_name": "seed"},
        MetaField.VARIATION_SEED: {"field_name": "variation_seed"},
        MetaField.VARIATION_STRENGTH: {"field_name": "variation_strength"},
        MetaField.STEPS: {"field_name": "steps"},
        MetaField.CFG: {"field_name": "cfg"},
        MetaField.SAMPLER_NAME: {"field_name": "sampler_name"},
        MetaField.SCHEDULER: {"field_name": "scheduler"},  
    }, 
    },  
}
```
In my situation I did need to _re-include_ some of the basic information (e.g., cfg, steps, etc.) as the metadata for these fields were not always getting picked up by the `update_pnginfo_dict` function in the `capture.py` file.  You'll notice that I have included additional `Metafields`, which were needed report the correct seed or variation seed (e.g., strenght/weight > 0).  This requires a little bit more editing to ensure that the fields are getting report and used correctly:

- Adding fields to the list of Metafields 
- Updating  `update_pnginfo_dict` function in the `capture.py` file

First up is adding the additional fields to `\defs\meta.py`. The numbers aren't specific, but figured I would make them high-enough to avoid potential conflicts ... from what I can tell you can number them as you see fit (I spent a bit of time trying to ensure these didn't align back to something on Civitai ... they don't .... or at least not that I can tell)

```
    VARIATION_SEED = 90
    VARIATION_STRENGTH = 91
    VARIATION_WEIGHT = 92
```

Next up is adding some logic to the `update_pnginfo_dict` function to figure out if it needs to use the original or variation seed information.  I had to add some additional logic as one sampler used `variation_strength` while the other used `variation_weight` as its value name ... YMMV.  From the testing that I could tell ... the node doesn't seem to mind if variation seed information isn't there as it seems to just _skip_ it and not include it in the `inputs_before_sampler_node` value  (guess if want to be truly safe you could introduce some error checking logic .... I was too tired to push it and will re-visit if becomes a problem in the future)

```
#Get variation key for setting Seed or Variation Seed based upon variation value
strength = inputs_before_sampler_node.get(MetaField.VARIATION_STRENGTH, [])
weight = inputs_before_sampler_node.get(MetaField.VARIATION_WEIGHT, [])

if len(strength) > 0:
    if strength[0][1] == 0.0:
        update_pnginfo_dict(inputs_before_sampler_node, MetaField.SEED, "Seed")
    else:
        update_pnginfo_dict(inputs_before_sampler_node, MetaField.VARIATION_SEED, "Seed")
elif len(weight) > 0:
    if weight[0][1] == 0.0:
        update_pnginfo_dict(inputs_before_sampler_node, MetaField.SEED, "Seed")
    else:
        update_pnginfo_dict(inputs_before_sampler_node, MetaField.VARIATION_SEED, "Seed")     
else:
    update_pnginfo_dict(inputs_before_sampler_node, MetaField.SEED, "Seed")
```

Phew ... that was a pretty long winded update on how to solve this error.  Your mileage may vary, but these two solutions should get you a lot closer if not all the way.  Good Luck!!!
